//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptitudorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestDetail
    {
        public TestDetail()
        {
            this.UserMarks = new HashSet<UserMark>();
        }
    
        public int Id { get; set; }
        public int ClassId { get; set; }
        public string Name { get; set; }
        public int Test_Time { get; set; }
        public int Test_Max { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<UserMark> UserMarks { get; set; }
    }
}
