//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptitudorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPaper
    {
        public int Id { get; set; }
        public int TestId { get; set; }
        public string Question { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string RightAns { get; set; }
        public int SubId { get; set; }
        public int ChapId { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
