//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptitudorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMark
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string College { get; set; }
        public int TestId { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual TestDetail TestDetail { get; set; }
    }
}
